### ISSUE TITLE
Remove any "helpful" comments in the forum and the readme about installing OpenCL drivers

### ISSUE THREAD

**Issue by KeithMyers** [efmer/boinctasks-js#100]
Remove any "helpful" comments in the forum and the readme about installing OpenCL drivers.

Just confuses new users with the JS product.

Also, same goes for installing ubuntu-drivers.  The user should already have a working system before tackling the installation of the JS product.

Too cryptic a help statement here. "If your see Unable to connect, the computer is found but the password might be wrong or the computer running BoincTasks Js isn’t allowed to connect."

Just post that you need the remote computers have <allow_remote_gui_rpc>1</allow_remote_gui_rpc> toggled on in the BOINC cc_config.xml file.

All comments are from direct interaction helping a new user trying to install BoincTasks.js today.

**Comment by efmer** [comment]
I don't think this in the BoincTasks Js header of the Forum.
There is certainly some old stuff on the forum that is no longer relevant.

If you want go to the forum and add your comments, that should help the users most.

https://efmer.com/ doesn't say you have to install anything, not what I can find.
Most Linux version should work out of the box, but some might not.

**Comment by KeithMyers** [comment]
I am responding to the issues of a teammate that has tried to install BoincTasks.js to his network. These are his comments and failures.
[quote]
I've got my 'local machine' set up to show all projects and tasks that I'm currently running on my 5950X/3080Ti system that I call GWG-PC3.  My other computer, GWG-PC2, does not show up when I've selected GWG-PC2 on GWG-PC3.  It says under 'status' - "Not connected, (df)".

I have read the "BoincTasks Js" webpage and there are some things I don't quite understand.

Connect to BoincTasks Js:

In BoincTasks Js , select ‘Computer->Find‘.

Next press Start.

If your see Unable to connect, the computer is found but the password might be wrong or the computer running BoincTasks Js isn’t allowed to connect.
[/quote]

[quote]
I see "add computer" (or something like that), but when I do click on it I do not get the other computer to link up, I get a "Not connected, error" message in the status column.

Also, in the webpage for BoincTasks Js, it says:

OpenCL:

Make sure the GPU drivers are installed:

‘sudo ubuntu-drivers autoinstall’

The OpenCL interface might not be installed, do so with

‘sudo apt install ocl-icd-libopencl1’

So to be sure, I tried to install them, and I got this:
[/quote]

[https://live.staticflickr.com/65535/52778426103_7b6ed93797_h.jpg]

[quote]So now I'm stumped.  What should I do?[/quote]

**Comment by efmer** [comment]
Use the BOINC Manager on the system you want to connect to and see if the logging shows the reason.
Generally it show refused something.

if you changed anything in cc_config.xml, the BOINC client needs to be restarted for this to work.

The GPU drivers have nothing to do with the connection.
[quote]So to be sure, I tried to install them, and I got this: [/quote]
‘sudo apt install ocl-icd-libopencl1’ says already installed so you are fine.

**Comment by efmer** [comment]
"Just post that you need the remote computers have <allow_remote_gui_rpc>1</allow_remote_gui_rpc> toggled on in the BOINC cc_config.xml file."
Is less safe and if you need this, you didn't include the allowed IP address, but this doesn't work if you have an automatically assigned IP address.

**Comment by KeithMyers** [comment]
He has no issues locally with the client or the Manager on the remote host.  I asked him if he had set the remote host to receive remote rpc's and haven't seen his response.  I am pretty positive that is all that he needs to do.

I alread gave him my response to his help request about setting the cc_config parameter or the option of a remote_hosts file.

My raising of this issue is in response to his getting lead completely astray with the OpenCL non-sense from the BoincTasks.js forum and help pages.

**Comment by efmer** [comment]
I adjusted the help pages.

**Comment by KeithMyers** [comment]
Thanks.  The next noobie will appreciate that I'm sure.
BTW, have you looked into the issue with BT an apps with versions 0.00 yet?  As long as I have your attention.
Never mind.  See you responded in the forum to my post.
