### ISSUE TITLE
Boinctasks-js crashes with segmentation fault

### ISSUE THREAD

**Issue by gj82854** [efmer/boinctasks-js#103]
Boinctasks-js crashes approximately every 2 days with a sig=11 (segmentation fault). The timing of the crash is somewhat load related. The more activity being tracked in Boinctasks-js the sooner the crash occurs. Set history to only keep 1 day but that made no difference in the crash frequency.  Boinctasks-js is 1.33 release running on Fedora 38 Linux. 

LOG:

Jun 09 07:45:14 foxtrot systemd[1]: Mounting var-lib-snapd-snap-boinctasks\x2djs-33.mount - Mount unit for boinctasks-js, revision 33...
Jun 09 07:45:14 foxtrot systemd[1]: Mounting var-lib-snapd-snap-boinctasks\x2djs-37.mount - Mount unit for boinctasks-js, revision 37...
Jun 09 07:45:14 foxtrot systemd[1]: Mounted var-lib-snapd-snap-boinctasks\x2djs-33.mount - Mount unit for boinctasks-js, revision 33.
Jun 09 07:45:14 foxtrot systemd[1]: Mounted var-lib-snapd-snap-boinctasks\x2djs-37.mount - Mount unit for boinctasks-js, revision 37.
Jun 09 08:21:40 foxtrot systemd[2265]: Started snap.boinctasks-js.boinctasks-js.e191ceb3-be55-4d8f-bcb4-4a3304150dc4.scope.
Jun 09 08:21:45 foxtrot boinctasks-js[3548]: Failed to load module "pk-gtk-module"
Jun 09 08:21:45 foxtrot boinctasks-js[3548]: Failed to load module "pk-gtk-module"
Jun 09 08:21:47 foxtrot audit[3682]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3682 comm="boinctasks-js
" exe="/snap/boinctasks-js/37/boinctasks-js" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f3842842c7f code=0x50000
Jun 09 08:21:47 foxtrot audit[3682]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3682 comm="boinctasks-js
" exe="/snap/boinctasks-js/37/boinctasks-js" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f3842842c7f code=0x50000
Jun 09 08:21:47 foxtrot audit[3682]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3682 comm="boinctasks-js
" exe="/snap/boinctasks-js/37/boinctasks-js" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f3842842c7f code=0x50000
Jun 09 08:21:47 foxtrot audit[3682]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3682 comm="boinctasks-js
" exe="/snap/boinctasks-js/37/boinctasks-js" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f3842842c7f code=0x50000
Jun 09 08:22:22 foxtrot systemd[2265]: Started snap.boinctasks-js.boinctasks-js.16c9d3c8-a1f2-4022-8d39-e3039607feba.scope.
Jun 09 08:22:23 foxtrot boinctasks-js[3748]: Failed to load module "pk-gtk-module"
Jun 09 08:22:23 foxtrot boinctasks-js[3748]: Failed to load module "pk-gtk-module"
Jun 09 08:22:23 foxtrot audit[3831]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3831 comm="boinctasks-js
" exe="/snap/boinctasks-js/37/boinctasks-js" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f4a3efcac7f code=0x50000
Jun 09 08:22:23 foxtrot audit[3831]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3831 comm="boinctasks-js
" exe="/snap/boinctasks-js/37/boinctasks-js" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f4a3efcac7f code=0x50000
Jun 09 08:22:23 foxtrot audit[3831]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3831 comm="boinctasks-js
" exe="/snap/boinctasks-js/37/boinctasks-js" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f4a3efcac7f code=0x50000
Jun 09 08:22:23 foxtrot audit[3831]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3831 comm="boinctasks-js
" exe="/snap/boinctasks-js/37/boinctasks-js" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f4a3efcac7f code=0x50000
Jun 14 03:00:52 foxtrot boinctasks-js_boinctasks-js.desktop[3548]: <--- Last few GCs --->
Jun 14 03:00:52 foxtrot boinctasks-js_boinctasks-js.desktop[3548]: [3548:0x2bce00000000] 412748440 ms: Mark-sweep (reduce) 3157.8 (3226.4) -> 3065.0 (3130.4) MB, 47.0
 / 0.0 ms  (average mu = 0.999, current mu = 1.000) last resort GC in old space requested
Jun 14 03:00:52 foxtrot boinctasks-js_boinctasks-js.desktop[3548]: [3548:0x2bce00000000] 412748498 ms: Mark-sweep (reduce) 3065.0 (3130.4) -> 3064.9 (3117.6) MB, 58.1
 / 0.0 ms  (average mu = 0.999, current mu = 0.000) last resort GC in old space requested
Jun 14 03:00:52 foxtrot boinctasks-js_boinctasks-js.desktop[3548]: <--- JS stacktrace --->
Jun 14 03:00:52 foxtrot kernel: boinctasks-js[3548]: segfault at 0 ip 0000563d7f24cf28 sp 00007ffce47358e0 error 6 in boinctasks-js[563d7aae1000+6271000] likely on CP
U 2 (core 2, socket 0)
Jun 14 03:00:52 foxtrot audit[3548]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3548 comm="boinctasks
-js" exe="/snap/boinctasks-js/37/boinctasks-js" sig=11 res=1
Jun 14 03:01:37 foxtrot systemd-coredump[14030]: Process 3548 (boinctasks-js) of user 1000 dumped core.
                                                 #0  0x0000563d7f24cf28 n/a (boinctasks-js + 0x6110f28)
                                                 #1  0x0000563d7c898777 n/a (boinctasks-js + 0x375c777)
                                                 #2  0x0000563d7c897da5 n/a (boinctasks-js + 0x375bda5)
                                                 #3  0x0000563d7c946525 n/a (boinctasks-js + 0x380a525)
                                                 #4  0x0000563d7ab1c304 n/a (boinctasks-js + 0x19e0304)
                                                 #5  0x0000563d7ab1c084 _ZN2v88internal11FactoryBaseINS0_7FactoryEE19NewRawOneByteStringEiNS0_14AllocationTypeE (boinc
tasks-js + 0x19e0084)
                                                 #6  0x0000563d7ab1bc60 _ZN2v88internal6String11SlowFlattenEPNS0_7IsolateENS0_6HandleINS0_10ConsStringEEENS0_14Allocat
ionTypeE (boinctasks-js + 0x19dfc60)
                                                 #7  0x0000563d7adc1970 n/a (boinctasks-js + 0x1c85970)
                                                 #8  0x0000563d7adc1899 n/a (boinctasks-js + 0x1c85899)
                                                 #9  0x0000563d7f7b3718 n/a (boinctasks-js + 0x6677718)
                                                 #10 0x0000563d7f74c8db n/a (boinctasks-js + 0x66108db)
                                                 #14 0x0000563d7f74b33b n/a (boinctasks-js + 0x660f33b)
                                                 #15 0x0000563d7f74b118 n/a (boinctasks-js + 0x660f118)
                                                 #16 0x0000563d7ab21edc n/a (boinctasks-js + 0x19e5edc)
                                                 #17 0x0000563d7ab1fdf7 _ZN2v88internal9Execution4CallEPNS0_7IsolateENS0_6HandleINS0_6ObjectEEES6_iPS6_ (boinctasks-js
 + 0x19e3df7)
                                                 #18 0x0000563d7cbf7b80 _ZN2v88Function4CallENS_5LocalINS_7ContextEEENS1_INS_5ValueEEEiPS5_ (boinctasks-js + 0x3abbb80
)
                                                 #19 0x0000563d80aff1a3 n/a (boinctasks-js + 0x79c31a3)
                                                 #20 0x0000563d80b1220f n/a (boinctasks-js + 0x79d620f)
                                                 #21 0x0000563d80c3a4c1 n/a (boinctasks-js + 0x7afe4c1)
                                                 #22 0x0000563d80c3c4e4 n/a (boinctasks-js + 0x7b004e4)
                                                 #23 0x0000563d80c4173f n/a (boinctasks-js + 0x7b0573f)
                                                 #24 0x0000563d7f1398ff n/a (boinctasks-js + 0x5ffd8ff)
                                                 #25 0x0000563d7f13ebfc n/a (boinctasks-js + 0x6002bfc)
                                                 #26 0x0000563d7f1308be uv_run (boinctasks-js + 0x5ff48be)
                                                 #27 0x0000563d7f24d544 n/a (boinctasks-js + 0x6111544)
                                                 #28 0x0000563d7aec1ebe n/a (boinctasks-js + 0x1d85ebe)
                                                 #29 0x0000563d7ab300b2 n/a (boinctasks-js + 0x19f40b2)
                                                 #30 0x0000563d7ab2fb5e n/a (boinctasks-js + 0x19f3b5e)
                                                 #31 0x0000563d7fcfe3f7 n/a (boinctasks-js + 0x6bc23f7)
                                                 #32 0x00007f31cb9d8537 n/a (/snap/boinctasks-js/37/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4 + 
0x4c537)
░░ Subject: Process 3548 (boinctasks-js) dumped core
░░ Process 3548 (boinctasks-js) crashed and dumped core.
Jun 14 03:01:38 foxtrot systemd[2265]: snap.boinctasks-js.boinctasks-js.e191ceb3-be55-4d8f-bcb4-4a3304150dc4.scope: Consumed 14h 44min 35.631s CPU time.
Jun 14 03:01:52 foxtrot abrt-notification[14090]: Process 3548 (boinctasks-js) crashed in ??()
░░ Subject: ABRT has detected unexpected termination: boinctasks-js
░░ boinctasks-js killed by SIGSEGV
░░ #1 [boinctasks-js] 3b133cd8fa256cfef48abc24e89f92bd19fd9401+101781288
░░ #2 [boinctasks-js] 3b133cd8fa256cfef48abc24e89f92bd19fd9401+58050423
░░ #3 [boinctasks-js] 3b133cd8fa256cfef48abc24e89f92bd19fd9401+58047909
░░ #4 [boinctasks-js] 3b133cd8fa256cfef48abc24e89f92bd19fd9401+58762533
░░ #5 [boinctasks-js] 3b133cd8fa256cfef48abc24e89f92bd19fd9401+27132676

**Comment by efmer** [comment]
I will make a new build, with some fixes.
Was unable to build a snap from the latest release, let's see if they Snap store resolved that issuel.

**Comment by efmer** [comment]
Just released 1.34. -> Snapstore.
Install latest candidate 1.34 (Source button)

Added a once a day reload in Extra->BoincTasks setting -> Restart at check and set time.

It might be a memory leak, I remove potential leaks, but it's almost impossible to find them.

**Comment by gj82854** [comment]
snap refresh boinctasks-js shows 1.3.3 as the latest release and issues message: No Updates Available
