### ISSUE TITLE
Boinctasks-JS Continues to Fail

### ISSUE THREAD

**Issue by gj82854** [efmer/boinctasks-js#109]
Boinctasks-JS continues to fail and, depending on workload, could not stay up 24 hours. Workload being defined as the number of WUs starting and ending on tracked hosts. Large numbers of hosts with short running jobs seems to reduce the uptime. Following information seems to indicate a Process Out of Memory error. Latest failure:

Aug 16 15:41:36 foxtrot systemd-coredump[25450]: [🡕] Process 20907 (boinctasks-js) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 20907:
                                                 #0  0x00007f365bf4be87 n/a (/lib/x86_64-linux-gnu/libc-2.27.so + 0x3ee87)
                                                 #1  0x00005598d5a51c1b n/a (boinctasks-js + 0x94b6c1b)
                                                 #2  0x00005598cfa9c1b6 _ZN2v88internal2V823FatalProcessOutOfMemoryEPNS0_7IsolateEPKcRKNS_10OOMDetailsE (boinctasks-js + 0x35011b6)
                                                 #3  0x00005598cfc5286b _ZN2v88internal13HeapAllocator34AllocateRawWithRetryOrFailSlowPathEiNS0_14AllocationTypeENS0_16AllocationOriginEN>
                                                 #4  0x00005598cfc30fd9 _ZN2v88internal7Factory15NewFillerObjectEiNS0_19AllocationAlignmentENS0_14AllocationTypeENS0_16AllocationOriginE >
                                                 #5  0x00005598d0066324 n/a (boinctasks-js + 0x3acb324)
                                                 #6  0x00005598ce554976 n/a (boinctasks-js + 0x1fb9976)
                                                 #7  0x00005598ce5f3add n/a (boinctasks-js + 0x2058add)
                                                 #8  0x00005598ce5f3c28 n/a (boinctasks-js + 0x2058c28)
                                                 #9  0x00005598e00be3b5 n/a (n/a + 0x0)
                                                 #10 0x00005598e009352e n/a (n/a + 0x0)
                                                 #11 0x00005598e0105aa0 n/a (n/a + 0x0)
                                                 #12 0x00005598ce4bb69c n/a (boinctasks-js + 0x1f2069c)
                                                 #13 0x00005598ce4bb3c7 n/a (boinctasks-js + 0x1f203c7)
                                                 #14 0x00005598cfbc2514 n/a (boinctasks-js + 0x3627514)
                                                 #15 0x00005598cfbc1a58 _ZN2v88internal9Execution4CallEPNS0_7IsolateENS0_6HandleINS0_6ObjectEEES6_iPS6_ (boinctasks-js + 0x3626a58)
                                                 #16 0x00005598cfab691b _ZN2v88Function4CallENS_5LocalINS_7ContextEEENS1_INS_5ValueEEEiPS5_ (boinctasks-js + 0x351b91b)
                                                 #17 0x00005598d5999039 n/a (boinctasks-js + 0x93fe039)
                                                 #18 0x00005598d59ae945 n/a (boinctasks-js + 0x9413945)
                                                 #19 0x00005598d5b43cd7 n/a (boinctasks-js + 0x95a8cd7)
                                                 #20 0x00005598d5b45c9e n/a (boinctasks-js + 0x95aac9e)
                                                 #21 0x00005598d5b4abad n/a (boinctasks-js + 0x95afbad)
                                                 #22 0x00005598d5b4b699 n/a (boinctasks-js + 0x95b0699)
                                                 #23 0x00005598ce826737 n/a (boinctasks-js + 0x228b737)
                                                 #24 0x00005598ce82b793 n/a (boinctasks-js + 0x2290793)
                                                 #25 0x00005598ce81d0a6 uv_run (boinctasks-js + 0x22820a6)
                                                 #26 0x00005598ce999f91 n/a (boinctasks-js + 0x23fef91)
                                                 #27 0x00005598d1be75ed n/a (boinctasks-js + 0x564c5ed)
                                                 #28 0x00005598d1c057b5 n/a (boinctasks-js + 0x566a7b5)
                                                 #29 0x00005598d1c051c9 n/a (boinctasks-js + 0x566a1c9)
                                                 #30 0x00005598d1c05f15 n/a (boinctasks-js + 0x566af15)
                                                 #31 0x00005598d1c66eeb n/a (boinctasks-js + 0x56cbeeb)
                                                 #32 0x00007f3660b6e537 n/a (/snap/boinctasks-js/41/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4 + 0x4c537)
                                                 ELF object binary architecture: AMD x86-64
Aug 16 15:41:37 foxtrot systemd[1]: systemd-coredump@4-25449-0.service: Deactivated successfully.
Aug 16 15:41:37 foxtrot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@4-25449-0 comm="systemd" exe="/usr/>
Aug 16 15:41:37 foxtrot systemd[1]: systemd-coredump@4-25449-0.service: Consumed 20.412s CPU time.
Aug 16 15:41:37 foxtrot audit: BPF prog-id=415 op=UNLOAD
Aug 16 15:41:37 foxtrot audit: BPF prog-id=414 op=UNLOAD
Aug 16 15:41:37 foxtrot audit: BPF prog-id=413 op=UNLOAD
Aug 16 15:41:37 foxtrot systemd[2240]: snap.boinctasks-js.boinctasks-js.f73bb6ac-ced5-4ebe-856f-bb9d13223c16.scope: Consumed 13h 58min 51.086s CPU time.
Aug 16 15:41:37 foxtrot audit: BPF prog-id=349 op=UNLOAD
Aug 16 15:41:49 foxtrot abrtd[939]: Size of '/var/spool/abrt' >= 5000 MB (MaxCrashReportsSize), deleting old directory 'ccpp-2023-08-13-23:57:41.789912-13627'
Aug 16 15:41:51 foxtrot abrt-server[25467]: Unsupported container technology
Aug 16 15:41:51 foxtrot abrt-server[25467]: Lock file '.lock' was locked by process 25470, but it crashed?
Aug 16 15:41:52 foxtrot abrt-applet[2870]: g_app_info_should_show: assertion 'G_IS_APP_INFO (appinfo)' failed
Aug 16 15:41:52 foxtrot abrt-notification[25511]: [🡕] Process 20907 (boinctasks-js) crashed in ??()

Boinctasks-JS doesn't stay up long enough to be a useful product.  I tried setting history to 0 but the program doesn't accept 0. It is the only program running on a 16GB system. It could be possible that 16GB isn't enough due to JAVA being a huge memory consumer.

**Comment by efmer** [comment]
I suggest installing the DEB instead of the SNAP version.
To do so remove SNAP BoincTasks JS 
Download and install the DEB https://efmer.com/boinctasks-js/boinctasks-js-download/
There might be some memory leaking but not more than a couple of mega bytes a day, not something to worry about after a day.

**Comment by gj82854** [comment]
This is running on Fedora 38. Running the .deb version isn't an option. it's more than a couple of meg per day. One process of Boinctasks-JS has grown from about 253M at startup to 3.6G of resident memory in less than one day. As stated previously, it can fail in less than one day of running depending on work being tracked.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by gj82854** [comment]
I will take a look at this and see if I can use it....

The process that seems to be the problem is the one with --type=renderer in the command line.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by efmer** [comment]
Right, that's what I noticed, a library in the renderer seems to be causing the problem.
So I'm removing the library and am rewriting all renderers, a significant amount of work.

**Comment by gj82854** [comment]
Unfortunately, the install of the .rpm fails due to conflicts with existing packages.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by efmer** [comment]
Probably fixed in 2.0
