### ISSUE TITLE
Boinctasks Crashes

### ISSUE THREAD

**Issue by gj82854** [efmer/boinctasks-js#124]
After installing Boinctasks-Js 2.0, it continues to fail from time to time. I was able to capture last failure data:

Sep 26 22:15:16 meerkat2 boinctasks-js.desktop[74076]: <--- Last few GCs --->
Sep 26 22:15:16 meerkat2 boinctasks-js.desktop[74076]: [74076:0x3ec4003bc000] 187044107 ms: Mark-Compact (reduce) 3435.3 (3503.5) -> 3400.6 (3463.0) MB, 12.65 / 0.00 ms  (average mu = 1.000, current mu = 1.000) last resort; GC in old space requested
Sep 26 22:15:16 meerkat2 boinctasks-js.desktop[74076]: [74076:0x3ec4003bc000] 187044125 ms: Mark-Compact (reduce) 3400.6 (3463.0) -> 3400.6 (3453.0) MB, 18.20 / 0.00 ms  (average mu = 0.999, current mu = 0.001) last resort; GC in old space requested
Sep 26 22:15:16 meerkat2 boinctasks-js.desktop[74076]: <--- JS stacktrace --->
Sep 26 22:15:16 meerkat2 boinctasks-js.desktop[74076]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Sep 26 22:15:16 meerkat2 systemd[1945]: app-gnome-boinctasks\x2djs-74076.scope: Consumed 5h 20min 6.912s CPU time.

**Comment by gj82854** [comment]
Three days later it failed again:
Sep 29 05:33:23 meerkat2 boinctasks-js.desktop[84223]: <--- Last few GCs --->
Sep 29 05:33:23 meerkat2 boinctasks-js.desktop[84223]: [84223:0x3500003bc000] 164556751 ms: Mark-Compact (reduce) 3420.5 (3471.3) -> 3414.9 (3456.3) MB, 13.04 / 0.00 ms  (average mu = 0.999, current mu = 0.997) last resort; GC in old space requested
Sep 29 05:33:23 meerkat2 boinctasks-js.desktop[84223]: [84223:0x3500003bc000] 164556768 ms: Mark-Compact (reduce) 3414.9 (3456.3) -> 3414.9 (3451.1) MB, 16.95 / 0.00 ms  (average mu = 0.998, current mu = 0.001) last resort; GC in old space requested
Sep 29 05:33:23 meerkat2 boinctasks-js.desktop[84223]: <--- JS stacktrace --->
Sep 29 05:33:23 meerkat2 boinctasks-js.desktop[84223]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Sep 29 05:33:47 meerkat2 systemd[1945]: app-gnome-boinctasks\x2djs-84223.scope: Consumed 5h 17min 38.349s CPU time.

**Comment by efmer** [comment]
It might be something in the framework and not in the program itself, so maybe I can build again at a later time.
We are now at 2.2, but I don't expect that will change thing much.

To check https://stackoverflow.com/questions/69827243/how-to-properly-debug-electron-memory-issues
https://www.electronjs.org/blog/v8-memory-cage
Search electron --max-old-space-size

Or someone can make a local build not using the Snap environment.

**Comment by gj82854** [comment]
This is not a snap version. I'm using a deb version of the build.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by efmer** [comment]
Go to Extra -?> BoincTasks settings -> at startup check Restart and add a time.
Now BoincTasks Js will restart every day.....

**Comment by gj82854** [comment]
Unfortunately, depending on workload that won't help. Sometimes the workload is such that it won't last 24 hours. It is tracking as many as 12000 tasks at times. I tried setting the history to 0 days but it wouldn't accept it just in case that might free up a small amount of memory. I may have to go back to the Windows based version at some point.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
You should be able to disable history Settings, at Timing set the second line (Refresh) to 0.

**Comment by efmer** [comment]
Did disabling History had any result, just released V 2.3

**Comment by gj82854** [comment]
No sir, it did not

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
Ok, thanks for reporting

**Comment by gj82854** [comment]
It is related to the number of tasks processed. If I process short running tasks (tasks that run in under 1 hour) it fails very quickly (sometimes under a day). If I switch to a project with longer running tasks it will work for as long as two to three days. There seems to be a limit on the number of tasks processed. Longer running tasks reach that limit much less quickly.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
Interesting that might help.
Do you keep the windows open or do you close it and open it.
What Linux distribution do you use?

**Comment by gj82854** [comment]
The window stays open 24/7 (or until it fails) then I just restart the app (no reboot). This happened on Fedora 39 and now it is running on Ubuntu 22.04.3 LTS with all patches current. Results were the same on both platforms. To me, the memory problem seems to be within the app address space. No other process(es) on the system is/are impacted by this issue.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
Can you close the windows and see how long it runs?
I'm using the Snap version on my Ubuntu machine and I checked the memory usage that is well within the max limit of 4G, not even close....
So it might be a problem with the DEB version.
I will add a memory window to check and log memory usage.

**Comment by gj82854** [comment]
I'm not sure what you mean by windows. The only app running on this machine is BoincTasks-JS. That is also, the only window open. When it fails, I'm looking at the desktop. I originally tried the Snap version and had the same problem. You recommended going to the .deb version due to perhaps some framework issue. Symptoms are the same for me regardless of the version.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
OK the problem is not tied to the Snap or Deb version, it's on both.
Try closing the BoincTasks JS window, that way it uses less resources.
How many tasks do you have?

**Comment by gj82854** [comment]
I case it makes a difference, I'm monitoring 4000 tasks across 6 machines and process about 3000 tasks per day. These tasks are running approximately an hour each and BoincTasks-JS runs about 24 to 36 hours before failing. When it failed within 24 hours, I was monitoring approx 7000 tasks and returning close to 8000 per day. Each task runs about 30 minutes each

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
Just press the X close that will actually move the app to the background.
on Linux minimize is about the same thing.
The only way to close the program is by File -> Exit.

**Comment by gj82854** [comment]
OK... Done. BoincTasks-JS still running in the background. Top command shows 1123.0G Virtual and 1.9G Resident memory use. System is using 4.5G out of 32G

System has been up one day (Last time it failed, I applied patches to the OS and rebooted).

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
I added V2.4 deb only for testing.
Made some changes and added memory logging.
It works fine on my Ubuntu machine.
https://efmer.com/boinctasks-js/boinctasks-js-download/

Once started select Extra -> Debug -> Memory usage.
This will show a window and logs data to a file.

**Comment by gj82854** [comment]
V2.4 has been installed, memory debug has been turned on and window is open.

NOTE: when running with window minimized under V2.2 release, the app stayed up 4 days and was still running when I shut it down to install V2.4. I would think that might point to the problem being in the windowing system part of the code. Just a guess of course.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
Right, I made some changes to the Task display as the most likely source of memory usage.
It's best to close the window, that way it uses less CPU time.

**Comment by gj82854** [comment]
Closing the window makes it almost useless to me as I use it as a real time monitor. If I close the window, I won't be able to see host status/issues unless I take some overt action (open the window).

It runs on a small (physically (4" by 4" by 1") and resource wise) system dedicated to it. CPU use is very small with the window open. Under 1%.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
It should work just fine when you keep the window open, this works fine on my Ubuntu machine.

**Comment by gj82854** [comment]
After about 1 day, the limit heap size is 4194048KB, Used Heap Size is 2849439KB, Heap Size is 2960272KB, Total Available Size is 1199874KB, Total Physical Size is 3038140KB

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by gj82854** [comment]
BoincTask-Js app failed.

Only one line was written to debug .csv file and that was at the start of the app. Is that the way it is supposed to work? File attached. Last time I looked available heap was down to 511000KB. I assume it ran out of heap.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
No the file should record as it does on my system, I will make some changes.
Still a puzzle.
Do you use projects that have very short tasks?
How many tasks do you have on your computers?

If I get these last two I can try to replicate.

**Comment by gj82854** [comment]
I run a variety of projects and switch between them at sporadic times. As stated previously, When I run short (Under an hour run time) tasks, Boinctasks-Js will fail in under a day. If i switch to tasks that run between 1 and 2 hours each, BoincTasks-Js will fail in about 2 days. Currently, I'm running tasks that run about 1 and 1/2 hours across 7 hosts. There is a total of about 3700 tasks being tracked by BoincTasks-Js. The problem seems to be related to the number of tasks. The more tasks I do in a day, the sooner BoincTasks-Js will fail. Just watching the memory monitor it seems that heap continues to grow until it reaches the limit. Like I mentioned in the previous note, it was down to about 511MB of available heap before it failed. I restarted after the last failure and reactivated the memory debug, It starts with about 4GB of heap but as of right now it has used 1.1GB with about 3GB available. Used heap continues to grow. I would think it should reach an equilibrium where new allocation is balanced by garbage collection. Once again, just a guess of course

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
I'm looking for a project with short tasks.
And find the leak in the millions items in the Heap.

**Comment by efmer** [comment]
I finally found a large memory leak at the point where the State is loaded.
This happens every time a new WU appears.
Have I found all the leaks? probably not, but maybe enough to make things more stable.

**Comment by gj82854** [comment]
That sounds like a good sign and seems to backup the symptoms I'm seeing. I assume the fix is quite available yet?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
I did my testing with out 6000 Tasks.
Refresh rate should be not less than 3 seconds.
The debug logging now shows the heap usages.
Yes the 2.4.1 is life, alternative download right here https://github.com/efmer/boinctasks-js/releases

**Comment by gj82854** [comment]
2.4.1 is now running. Memory debug now has button "Write Heap Snapshot to File", do I need to do anything with that?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by gj82854** [comment]
There are other errors showing up in the 2.4.1 release. Workunits are being tagged as undefined in the application column of the Tasks display. Didn't happen with 2.4. Additionally, there are applications being associated with the wrong project. EX: on my task display, Human Ventricular Cell Optimization is being associated with World Community Grid. That application should be associated with ***@***.***

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by efmer** [comment]
That's where I changed things, but I can reproduce the problem, so it should be easy to fix and soon.

**Comment by efmer** [comment]
Should be fixed in V2.4.2 https://efmer.com/boinctasks-js/boinctasks-js-download/

**Comment by gj82854** [comment]
Thank You... Version 2.4.2 is now running

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by gj82854** [comment]
This version has been running for several weeks and has not crashed. Memory debug display shows cache staying consistently below 1GB. I consider this issue resolved.

**Comment by efmer** [comment]
Perfect, it took me a week finding the needle, glad that is behind..
