### ISSUE TITLE
Blank Tasks tab from BoincTasks Js later than 2.0

### ISSUE THREAD

**Issue by Wedge009** [efmer/boinctasks-js#127]
Greetings.

I use BoincTasks Js on my Linux machine since I never could get BoincTasks classic working via Wine. I know version 2.2 has been out for a while, but I haven't seen anyone else report this issue so here we go:

I have a working configuration set-up fine for BoincTasks Js 2.0 but it looks like the releases after it have lost the ability to show anything in the Tasks tab:
![image](https://github.com/efmer/boinctasks-js/assets/13679322/f57d78fc-e6ff-45af-a8cb-a28ea8f029ee)
Note the task count at the bottom.

(It's also difficult to download BoincTasks Js since it's a large file and it seems the server disconnects frequently.)

Please advise what information you need to assist with debugging. (I assume this is a bug and not a feature.)

Edit: I use the debian packages from https://efmer.com/boinctasks-js/boinctasks-js-download/

**Comment by efmer** [comment]
Go to menu: Show and check Show CPU and  Show GPU.

**Comment by Wedge009** [comment]
So that's all it was? Perhaps they should be enabled as default, then. Thanks anyway.

**Comment by efmer** [comment]
Yes I added it as a new issue.
Should at least give a warning that both are not checked and you see nothing at all.
