### ISSUE TITLE
Nested tasks will not abort

### ISSUE THREAD

**Issue by stoneageman404** [efmer/boinctasks-js#13]
Where you have say 200 tasks waiting to run, showing as a single line and you select it and click abort, then accept the warning, the tasks do not abort. You have to expand them and abort them individually, which is not practical to do.
Running on Linux x64, snap V1.12

**Comment by efmer** [comment]
You can select the first, head to the bottom of the list, hold down the shift key and click on the last.
Next delete.

**Comment by stoneageman404** [comment]
Does not work for me. Last task does not select. Now running snap V1.14

**Comment by efmer** [comment]
I see, select doesn't work in the filter.

**Comment by efmer** [comment]
Fixed V 1.15, shows an instruction dialog, when you try to delete a filtered task.
