### ISSUE TITLE
Time column says 'Invalid' instead of time

### ISSUE THREAD

**Issue by KeithMyers** [efmer/boinctasks-js#130]
Time column says 'Invalid' instead of time for any tab like Messages or History.
[https://www.flickr.com/photos/astroimager/53699346974/in/dateposted-public/](https://www.flickr.com/photos/astroimager/53699346974/in/dateposted-public/)

**Comment by KeithMyers** [comment]
Any help here please!

**Comment by efmer** [comment]
I work on the project when I can.

I see a valid time, so it might be related to a local time format.
Check Show->Error Log see if there is an error.
Check Show->Debug, press copy and past the text in this issue.

**Comment by KeithMyers** [comment]
No errors shown in either Error Log or Debug Log

9:30:16 AM BoincTasks Js, V 2.4.2.
9:30:16 AM Electron: V 28.1.3.
9:30:16 AM Node: V 18.18.2.
9:30:16 AM System running on platform: linux ,architecture: x64.
9:30:16 AM Folder app: /home/keith/snap/boinctasks-js/57.
9:30:16 AM Folder data: (appData) /home/keith/snap/boinctasks-js/57/.config.
9:30:16 AM Folder data: (userData) /home/keith/snap/boinctasks-js/57/.config/BoincTasks Js.
9:30:16 AM Locale: en-US , US.
9:30:18 AM main, showApp showArg: arg is empty.
9:30:18 AM main, showApp actual: true.
9:30:18 AM Read state: Darksider.
9:30:18 AM Read state: Nano.
9:30:18 AM Read state: Numbskull.
9:30:18 AM Read state: Pi4.
9:30:18 AM Read state: Pipsqueek.
9:30:18 AM Read state: Rocinante.
9:30:18 AM Read state: Serenity.
9:30:18 AM Read state: midget.
9:30:18 AM Read state: tx2-nx.
9:30:18 AM buildCache add: Pi4 URL: https://asteroidsathome.net/boinc/ -&gt; Asteroids@home.
9:30:18 AM buildCache add: Pi4 URL: https://einstein.phys.uwm.edu/ -&gt; Einstein@Home.
9:30:18 AM buildCache add: Pi4 URL: http://gene.disi.unitn.it/test/ -&gt; TN-Grid Platform.
9:30:18 AM buildCache add: Pi4 URL: https://universeathome.pl/universe/ -&gt; Universe@Home.
9:30:18 AM buildCache add: Pi4 URL: http://www.rechenkraft.net/yoyo/ -&gt; yoyo@home.
9:30:18 AM buildCache add: midget URL: https://asteroidsathome.net/boinc/ -&gt; Asteroids@home.
9:30:18 AM buildCache add: midget URL: https://einstein.phys.uwm.edu/ -&gt; Einstein@Home.
9:30:18 AM buildCache add: midget URL: http://gene.disi.unitn.it/test/ -&gt; TN-Grid Platform.
9:30:18 AM buildCache add: midget URL: https://universeathome.pl/universe/ -&gt; Universe@Home.
9:30:18 AM buildCache add: midget URL: http://www.worldcommunitygrid.org/ -&gt; World Community Grid.
9:30:18 AM buildCache add: midget URL: http://www.rechenkraft.net/yoyo/ -&gt; yoyo@home.
9:30:18 AM buildCache add: Serenity URL: https://asteroidsathome.net/boinc/ -&gt; Asteroids@home.
9:30:18 AM buildCache add: Serenity URL: https://einstein.phys.uwm.edu/ -&gt; Einstein@Home.
9:30:18 AM buildCache add: Serenity URL: https://www.gpugrid.net/ -&gt; GPUGRID.
9:30:18 AM buildCache add: Serenity URL: http://milkyway.cs.rpi.edu/milkyway/ -&gt; Milkyway@home.
9:30:18 AM buildCache add: Serenity URL: http://numberfields.asu.edu/NumberFields/ -&gt; NumberFields@home.
9:30:18 AM buildCache add: Serenity URL: http://www.primegrid.com/ -&gt; PrimeGrid.
9:30:18 AM buildCache add: Serenity URL: http://radioactiveathome.org/boinc/ -&gt; Radioactive@Home.
9:30:18 AM buildCache add: Serenity URL: https://rnma.xyz/boinc/ -&gt; RamanujanMachine.
9:30:18 AM buildCache add: Serenity URL: http://gene.disi.unitn.it/test/ -&gt; TN-Grid Platform.
9:30:18 AM buildCache add: Serenity URL: https://universeathome.pl/universe/ -&gt; Universe@Home.
9:30:18 AM buildCache add: Serenity URL: http://www.worldcommunitygrid.org/ -&gt; World Community Grid.
9:30:18 AM buildCache add: Serenity URL: http://www.rechenkraft.net/yoyo/ -&gt; yoyo@home.
9:30:18 AM buildCache add: Nano URL: https://asteroidsathome.net/boinc/ -&gt; Asteroids@home.
9:30:18 AM buildCache add: Nano URL: https://einstein.phys.uwm.edu/ -&gt; Einstein@Home.
9:30:18 AM buildCache add: Nano URL: http://gene.disi.unitn.it/test/ -&gt; TN-Grid Platform.
9:30:18 AM buildCache add: Nano URL: http://www.rechenkraft.net/yoyo/ -&gt; yoyo@home.
9:30:18 AM buildCache add: tx2-nx URL: https://asteroidsathome.net/boinc/ -&gt; Asteroids@home.
9:30:18 AM buildCache add: tx2-nx URL: https://einstein.phys.uwm.edu/ -&gt; Einstein@Home.
9:30:18 AM buildCache add: tx2-nx URL: http://gene.disi.unitn.it/test/ -&gt; TN-Grid Platform.
9:30:18 AM buildCache add: tx2-nx URL: http://www.rechenkraft.net/yoyo/ -&gt; yoyo@home.
9:30:18 AM buildCache add: Darksider URL: https://asteroidsathome.net/boinc/ -&gt; Asteroids@home.
9:30:18 AM buildCache add: Darksider URL: https://einstein.phys.uwm.edu/ -&gt; Einstein@Home.
9:30:18 AM buildCache add: Darksider URL: https://www.gpugrid.net/ -&gt; GPUGRID.
9:30:18 AM buildCache add: Darksider URL: http://milkyway.cs.rpi.edu/milkyway/ -&gt; Milkyway@home.
9:30:18 AM buildCache add: Darksider URL: http://numberfields.asu.edu/NumberFields/ -&gt; NumberFields@home.
9:30:18 AM buildCache add: Darksider URL: http://www.primegrid.com/ -&gt; PrimeGrid.
9:30:18 AM buildCache add: Darksider URL: https://rnma.xyz/boinc/ -&gt; RamanujanMachine.
9:30:18 AM buildCache add: Darksider URL: http://gene.disi.unitn.it/test/ -&gt; TN-Grid Platform.
9:30:18 AM buildCache add: Darksider URL: https://universeathome.pl/universe/ -&gt; Universe@Home.
9:30:18 AM buildCache add: Darksider URL: http://www.worldcommunitygrid.org/ -&gt; World Community Grid.
9:30:18 AM buildCache add: Darksider URL: http://www.rechenkraft.net/yoyo/ -&gt; yoyo@home.
9:30:18 AM buildCache add: Pipsqueek URL: https://asteroidsathome.net/boinc/ -&gt; Asteroids@home.
9:30:18 AM buildCache add: Pipsqueek URL: https://einstein.phys.uwm.edu/ -&gt; Einstein@Home.
9:30:18 AM buildCache add: Pipsqueek URL: https://www.gpugrid.net/ -&gt; GPUGRID.
9:30:18 AM buildCache add: Pipsqueek URL: http://milkyway.cs.rpi.edu/milkyway/ -&gt; Milkyway@home.
9:30:18 AM buildCache add: Pipsqueek URL: http://numberfields.asu.edu/NumberFields/ -&gt; NumberFields@home.
9:30:18 AM buildCache add: Pipsqueek URL: http://www.primegrid.com/ -&gt; PrimeGrid.
9:30:18 AM buildCache add: Pipsqueek URL: https://rnma.xyz/boinc/ -&gt; RamanujanMachine.
9:30:18 AM buildCache add: Pipsqueek URL: http://gene.disi.unitn.it/test/ -&gt; TN-Grid Platform.
9:30:18 AM buildCache add: Pipsqueek URL: https://universeathome.pl/universe/ -&gt; Universe@Home.
9:30:18 AM buildCache add: Pipsqueek URL: http://www.worldcommunitygrid.org/ -&gt; World Community Grid.
9:30:18 AM buildCache add: Pipsqueek URL: http://www.rechenkraft.net/yoyo/ -&gt; yoyo@home.
9:30:18 AM buildCache add: Numbskull URL: https://asteroidsathome.net/boinc/ -&gt; Asteroids@home.
9:30:18 AM buildCache add: Numbskull URL: https://einstein.phys.uwm.edu/ -&gt; Einstein@Home.
9:30:18 AM buildCache add: Numbskull URL: https://www.gpugrid.net/ -&gt; GPUGRID.
9:30:18 AM buildCache add: Numbskull URL: http://milkyway.cs.rpi.edu/milkyway/ -&gt; Milkyway@home.
9:30:18 AM buildCache add: Numbskull URL: http://numberfields.asu.edu/NumberFields/ -&gt; NumberFields@home.
9:30:18 AM buildCache add: Numbskull URL: http://www.primegrid.com/ -&gt; PrimeGrid.
9:30:18 AM buildCache add: Numbskull URL: https://rnma.xyz/boinc/ -&gt; RamanujanMachine.
9:30:18 AM buildCache add: Numbskull URL: http://gene.disi.unitn.it/test/ -&gt; TN-Grid Platform.
9:30:18 AM buildCache add: Numbskull URL: https://universeathome.pl/universe/ -&gt; Universe@Home.
9:30:18 AM buildCache add: Numbskull URL: http://www.worldcommunitygrid.org/ -&gt; World Community Grid.
9:30:18 AM buildCache add: Numbskull URL: http://www.rechenkraft.net/yoyo/ -&gt; yoyo@home.
9:30:18 AM buildCache add: Rocinante URL: https://asteroidsathome.net/boinc/ -&gt; Asteroids@home.
9:30:18 AM buildCache add: Rocinante URL: https://einstein.phys.uwm.edu/ -&gt; Einstein@Home.
9:30:18 AM buildCache add: Rocinante URL: https://www.gpugrid.net/ -&gt; GPUGRID.
9:30:18 AM buildCache add: Rocinante URL: http://milkyway.cs.rpi.edu/milkyway/ -&gt; Milkyway@home.
9:30:18 AM buildCache add: Rocinante URL: http://numberfields.asu.edu/NumberFields/ -&gt; NumberFields@home.
9:30:18 AM buildCache add: Rocinante URL: http://www.primegrid.com/ -&gt; PrimeGrid.
9:30:18 AM buildCache add: Rocinante URL: https://rnma.xyz/boinc/ -&gt; RamanujanMachine.
9:30:18 AM buildCache add: Rocinante URL: https://www.sidock.si/sidock/ -&gt; SiDock@home.
9:30:18 AM buildCache add: Rocinante URL: http://gene.disi.unitn.it/test/ -&gt; TN-Grid Platform.
9:30:18 AM buildCache add: Rocinante URL: https://universeathome.pl/universe/ -&gt; Universe@Home.
9:30:18 AM buildCache add: Rocinante URL: http://www.worldcommunitygrid.org/ -&gt; World Community Grid.
9:30:18 AM buildCache add: Rocinante URL: http://www.rechenkraft.net/yoyo/ -&gt; yoyo@home.
9:30:22 AM Heap usage: 44561 KB, Total heap size: 60864 KB, Total allowed heap size: 1500000 KB.
9:31:01 AM Read state: Numbskull.
9:31:15 AM Authenticated (shadow): 192.168.50.100:31416, tx2-nx.
9:31:19 AM Read state: Rocinante.
9:31:35 AM Authenticated (shadow): 192.168.50.100:31416, tx2-nx.
9:31:49 AM Authenticated (shadow): 192.168.50.81:31416, Nano.
12:18:12 PM Read state: Darksider.
12:18:12 PM Read state: Nano.
12:18:12 PM Read state: Numbskull.
12:18:12 PM Read state: Pi4.
12:18:12 PM Read state: Pipsqueek.
12:18:12 PM Read state: Rocinante.
12:18:12 PM Read state: Serenity.
12:18:12 PM Read state: tx2-nx.
12:18:24 PM Read state: tx2-nx.
5:20:23 PM Read state: Darksider.
5:20:34 PM Authenticated (shadow): 192.168.50.145:31416, Darksider.
5:20:37 PM Authenticated (shadow): 192.168.50.145:31416, Darksider.
5:21:13 PM Authenticated (shadow): 192.168.50.145:31416, Darksider.
5:21:27 PM Authenticated (shadow): 192.168.50.145:31416, Darksider.
5:21:46 PM Read state: Numbskull.
5:21:55 PM Authenticated (shadow): 192.168.50.134:31416, Numbskull.
5:21:59 PM Authenticated (shadow): 192.168.50.134:31416, Numbskull.
5:22:21 PM Authenticated (shadow): 192.168.50.134:31416, Numbskull.
5:22:36 PM Authenticated (shadow): 192.168.50.134:31416, Numbskull.
5:22:52 PM Read state: Pipsqueek.
5:23:01 PM Authenticated (shadow): 192.168.50.11:31416, Pipsqueek.
5:23:13 PM Authenticated (shadow): 192.168.50.11:31416, Pipsqueek.
5:23:20 PM Read state: Pipsqueek.
5:23:20 PM Read state: Rocinante.
5:23:32 PM Authenticated (shadow): 192.168.50.207:31416, Rocinante.
5:23:32 PM Read state: Rocinante.
5:23:43 PM Authenticated (shadow): 192.168.50.207:31416, Rocinante.
5:23:55 PM Read state: Serenity.
5:24:04 PM Authenticated (shadow): 127.0.0.1:31416, Serenity.
5:24:09 PM Heap usage: 77536 KB, Total heap size: 100124 KB, Total allowed heap size: 1500000 KB.
5:24:15 PM Authenticated (shadow): 127.0.0.1:31416, Serenity.
5:24:18 PM Read state: Serenity.
5:24:26 PM Read state: Darksider.
5:24:58 PM Read state: Numbskull.
5:25:11 PM Read state: Rocinante.
5:25:35 PM Read state: Pipsqueek.
5:25:39 PM Read state: Numbskull.
5:25:45 PM Read state: Darksider.
5:25:51 PM Read state: Nano.
5:25:51 PM Read state: Pi4.
5:25:51 PM Read state: midget.
5:25:51 PM Read state: tx2-nx.
5:26:08 PM Authenticated (shadow): 192.168.50.145:31416, Darksider.
5:26:10 PM Authenticated (shadow): 192.168.50.134:31416, Numbskull.
5:26:13 PM Authenticated (shadow): 192.168.50.11:31416, Pipsqueek.
5:26:15 PM Authenticated (shadow): 192.168.50.207:31416, Rocinante.
5:26:17 PM Authenticated (shadow): 127.0.0.1:31416, Serenity.
5:26:26 PM Authenticated (shadow): 192.168.50.145:31416, Darksider.
5:26:28 PM Authenticated (shadow): 192.168.50.134:31416, Numbskull.
5:26:30 PM Authenticated (shadow): 192.168.50.11:31416, Pipsqueek.
5:26:32 PM Authenticated (shadow): 192.168.50.207:31416, Rocinante.
5:26:34 PM Authenticated (shadow): 127.0.0.1:31416, Serenity.
5:27:07 PM Authenticated (shadow): 192.168.50.145:31416, Darksider.
5:27:09 PM Authenticated (shadow): 192.168.50.134:31416, Numbskull.
5:27:11 PM Authenticated (shadow): 192.168.50.11:31416, Pipsqueek.
5:27:13 PM Authenticated (shadow): 192.168.50.207:31416, Rocinante.
5:27:15 PM Authenticated (shadow): 127.0.0.1:31416, Serenity.
6:43:39 PM Read state: Darksider.
6:43:39 PM Read state: Nano.
6:43:39 PM Read state: Numbskull.
6:43:39 PM Read state: Pi4.
6:43:39 PM Read state: Pipsqueek.
6:43:39 PM Read state: Rocinante.
6:43:39 PM Read state: Serenity.
6:43:39 PM Read state: tx2-nx.
6:45:17 PM Read state: Pipsqueek.
6:46:46 PM Read state: Darksider.
6:46:46 PM Read state: Pipsqueek.
11:13:21 PM Read state: Darksider.
11:13:21 PM Read state: Nano.
11:13:21 PM Read state: Numbskull.
11:13:21 PM Read state: Pi4.
11:13:21 PM Read state: Pipsqueek.
11:13:21 PM Read state: Rocinante.
11:13:21 PM Read state: Serenity.
11:13:21 PM Read state: tx2-nx.
11:13:23 PM Read state: Rocinante.
11:13:30 PM Heap usage: 153099 KB, Total heap size: 174088 KB, Total allowed heap size: 1500000 KB.
11:13:46 PM Read state: Darksider.
11:14:46 PM Authenticated (shadow): 127.0.0.1:31416, Serenity.
11:14:51 PM Read state: Pipsqueek.
11:15:05 PM Read state: Pipsqueek.
11:15:06 PM Authenticated (shadow): 192.168.50.100:31416, tx2-nx.
11:15:12 PM Read state: tx2-nx.
11:15:23 PM Authenticated (shadow): 192.168.50.81:31416, Nano.
11:15:28 PM Read state: Darksider.
11:15:28 PM Read state: Nano.
11:15:32 PM Read state: Rocinante.
11:18:42 AM Read state: Darksider.
11:18:42 AM Read state: Nano.
11:18:42 AM Read state: Numbskull.
11:18:42 AM Read state: Pi4.
11:18:42 AM Read state: Pipsqueek.
11:18:42 AM Read state: Rocinante.
11:18:42 AM Read state: Serenity.
11:18:42 AM Read state: midget.
11:18:42 AM Read state: tx2-nx.
11:18:48 AM Read state: Pipsqueek.
2:41:31 PM Read state: Darksider.
2:41:31 PM Read state: Nano.
2:41:31 PM Read state: Numbskull.
2:41:31 PM Read state: Pi4.
2:41:31 PM Read state: Pipsqueek.
2:41:31 PM Read state: Rocinante.
2:41:31 PM Read state: Serenity.
2:41:31 PM Read state: midget.
2:41:31 PM Read state: tx2-nx.
2:41:54 PM btTimer,gBusy, timeout.
2:42:04 PM btTimer,gBusy, timeout.
2:42:05 PM Authenticated (shadow): 192.168.50.100:31416, tx2-nx.
2:42:17 PM Read state: Numbskull.
2:42:17 PM Read state: Pipsqueek.
2:49:21 PM btTimer,gBusy, timeout.
3:14:23 PM btTimer,gBusy, timeout.
3:31:25 PM btTimer,gBusy, timeout.
3:33:50 PM Read state: Darksider.
3:33:50 PM Read state: Numbskull.
3:33:50 PM Read state: Pipsqueek.
3:33:50 PM Read state: Rocinante.
3:33:50 PM Read state: Serenity.
3:33:50 PM Read state: midget.
3:33:50 PM Read state: tx2-nx.
3:34:01 PM Read state: Numbskull.
3:34:41 PM Read state: Pipsqueek.
3:34:43 PM Read state: Rocinante.
5:15:30 PM Read state: Darksider.
5:15:30 PM Read state: Nano.
5:15:30 PM Read state: Numbskull.
5:15:30 PM Read state: Pi4.
5:15:30 PM Read state: Pipsqueek.
5:15:30 PM Read state: Rocinante.
5:15:30 PM Read state: Serenity.
5:15:30 PM Read state: tx2-nx.
5:17:02 PM Heap usage: 253232 KB, Total heap size: 276920 KB, Total allowed heap size: 1500000 KB.

BoincTasks Js, V 2.4.25:20:34 PM Error Logging [ConnectionsShadow,sendArrayNextShadow,data] No success: &lt;boinc_gui_rpc_reply&gt;
&lt;error&gt;No such project&lt;/error&gt;
&lt;/boinc_gui_rpc_reply&gt;
.
5:20:37 PM Error Logging [ConnectionsShadow,sendArrayNextShadow,data] No success: &lt;boinc_gui_rpc_reply&gt;
&lt;error&gt;No such project&lt;/error&gt;
&lt;/boinc_gui_rpc_reply&gt;
.


I don't understand your statement where you see a valid time in my Screenshot.  All I see in Invalid for Message or Invalid in the Completed column for History.

**Comment by KeithMyers** [comment]
Local time is UTC -8 DST Los Angeles 24 hour time format for the host.

**Comment by efmer** [comment]
The function toLocaleDateString(locale, options) used to generate the time string may not be supported on all systems.
An error message and a fallback to toLocaleDateString without parameters has been added.
