### ISSUE TITLE
Workunit name missing last part of the name

### ISSUE THREAD

**Issue by gj82854** [efmer/boinctasks-js#2]
Using V1.11 of Boinctasks-js but noticed the problem on V1.10 and V1.08. The workunit name is missing the last part of the name. This normally indicates the generation of the workunit. That part of the workunit is usually a _0, or _1, or _2 etc. It looks like the name was taken from the <wu-name> field in the client_state.xml file instead of the <name> field. The last part of the name helps to designate if the workunit is a resend or not.

**Comment by efmer** [comment]
V 1.12 table_results change wu -> wuName
