### ISSUE TITLE
Import computer list from Boinctasks "classic"

### ISSUE THREAD

**Issue by Le-zOU** [efmer/boinctasks-js#24]
Could there be an option to find/import computer list from Boinctasks "classic" ?
This way we can:
- keep Boinctasks installed
- install Boinctasks JS
- import computer lists during 1st launch (and other settings ? )
- uninstall Boinctasks 'classic"
- That would make the upgrade a lot easier :-)

**Comment by efmer** [comment]
I will make a migration page.
The computer xml file is compatible, so that would be easy.
The other settings are absolutely incompatible

**Comment by Le-zOU** [comment]
Thank you ! I appreciate the quick feedback !

**Comment by efmer** [comment]
Explanation added:
[](https://efmer.com/boinctasks-js-migrate-from-boinctasks/)

**Comment by Le-zOU** [comment]
Thank you,

I do not have a "settings" folder in my boinctasks js folder, even though I launched and exited Boinctasks js once already.

![image](https://user-images.githubusercontent.com/17430807/117109018-4e8bb880-ad84-11eb-975e-90c122d28ddb.png)

Also, Boinctasks Classic is in a eFMer subfolder
![image](https://user-images.githubusercontent.com/17430807/117109068-5f3c2e80-ad84-11eb-9673-1940ab16ac33.png)

**Comment by efmer** [comment]
It's really weird that the folder isn't there.
The text is MSF\eFMer\BoincTasks & MSF\BoincTasks Js\settings
I added:
If the MSF\BoincTasks Js\settings folder isn't there, go to the menu, View -> Sidebar Computers (BoincTasks Js). Uncheck and check the setting Sidebar Computers. This triggers a write and creates the settings folder.

**Comment by Le-zOU** [comment]
I manually created a folder named settings in C:\Users\**account**\AppData\Roaming\BoincTasks Js\
I copied the computers.xml file from the boinctasks folder

restarted boinctasks JS: all good

thx
