### ISSUE TITLE
CPU and Progress Percentages are Whole Numbers

### ISSUE THREAD

**Issue by gj82854** [efmer/boinctasks-js#3]
V1.11 is reporting only whole numbers for the CPU and Progress percentages. It seems it was reporting fractional percentages in V1.08 but changed in v1.10. BOINC client is reporting fractional percentages.

**Comment by efmer** [comment]
Use parseFloat.

    let cpu = parseInt(result.cpu);
    let cpu = parseFloat(result.cpu);

    let fraction = parseInt(result.fraction); 
    let fraction = parseFloat(result.fraction);
