### ISSUE TITLE
BoincTasks settings changes are not saved

### ISSUE THREAD

**Issue by TeeVeeEss** [efmer/boinctasks-js#74]
`12:48:08 Error Logging [Main,settings_boinctasks] Cannot read property 'language' of undefined
TypeError: Cannot read property 'language' of undefined at IpcMainImpl. (D:\progs\BoincTasks-Js\resources\app.asar\main.js:948:28) at IpcMainImpl.emit (events.js:315:20) at Object. (electron/js2c/browser_init.js:161:9692) at Object.emit (events.js:315:20).`
All my changes (Extra, BoincTasks settings) are ignored, the debug shows this error. Could be because I changed the default installation directory?
Version V1.23, Win 10 Prof, Locale nl, chosen Language at install: English

**Comment by efmer** [comment]
I copied the program folder from C:\Program Files\eFMer\BoincTasks-Js -> D:\BoincTasks-Js
Changing the language from English -> Nederlands works just fine.

There is probably something wrong with the stored settings file.
Exit BoincTasks Js and go to:
C:\Users\username\AppData\Roaming\BoincTasks Js\settings

Delete settings_boinctasks.json

Start BoincTasks Js.

**Comment by efmer** [comment]
ipcMain.on("settings_boinctasks", (renderer, settings) => {
  Add check for an undefined language, if so set to English.

**Comment by TeeVeeEss** [comment]
fyi: this is the current `settings_boinctasks.json` in my %appdata% folder:
```json
{"css":".bt_table { font-family: system; font-size: 1.0em;} ","refreshRate":2,"historyRefreshRate":60,"historyDelete":7,"socketTimeout":10,"fontSize":1,"language":"lang_english","languageIsSelected":"3"}
```
Followed your instructions to delete the file. After a restart I got the popup to select a language. After choosing English and trying to change the styling to `.bt_table { font-family: verdana; font-size: 1.0em;} ` and pressing "Apply changes": the window is not closed. Am I missing something?
The new `settings_boinctasks.json` is the same as the old one.

**Comment by efmer** [comment]
The Apply changes doen't close the window but does apply the changes.
I changed the font:
.bt_table { font-family: verdana; font-size: 1.0em;} 
The json file was updated and the changes are visible.

I have the same OS for testing.

**Comment by TeeVeeEss** [comment]
Strange. Every time I press Apply changes the error message about language `Cannot read property 'language' of undefined at IpcMainImpl` is produced. Any more info I can deliver?

**Comment by efmer** [comment]
As if the settings folder is somewhere else.
Show Debug Log 
Look for: Folder data: (userData) 
The folder should be accessible

**Comment by TeeVeeEss** [comment]
```13:43:55 BoincTasks Js, V 1.23.
13:43:55 Folder app: C:\Users\[username].
13:43:55 Folder data: (appData) C:\Users\[username]\AppData\Roaming.
13:43:55 Folder data: (userData) C:\Users\[username]\AppData\Roaming\BoincTasks Js.
13:43:55 Locale: nl , NL.
13:43:58 Read state: [ahost1].
13:43:58 Read state: [ahost2].
13:43:58 Read state: [ahost3].
13:43:58 Read state: [vhost4].
```
The fifth host is however not reported but visible 
![image](https://user-images.githubusercontent.com/17521100/129478124-111781d2-0bb2-41b6-a5b7-2fa99f0e0910.png)

**Comment by efmer** [comment]
Delete settings_boinctasks.json

Restart BoincTasks Js.

Don't change anything, only press Apply changes.

Does that produce an error.

**Comment by TeeVeeEss** [comment]
Only after a change from English to Dutch the Apply changes button works: it restarted BoincTasks! 
After that any changes (like setting system in stead of verdana) are applied direct without restarting BoincTasks
The fix you suggested should be enough. (Afk now, will check later tonight)

**Comment by efmer** [comment]
V 1.24
