### ISSUE TITLE
Adding new project not on list

### ISSUE THREAD

**Issue by stoneageman404** [efmer/boinctasks-js#75]
When adding a new project, it's not possible to add a project address which is not on the drop down list, as it just defaults to whatever is selected from the list. TN-grid is an example, http://gene.disi.unitn.it/test/

**Comment by efmer** [comment]
Fix: Always use the Project url.
Now it uses the one from the dropdown box even if the Project url was manually changed.

**Comment by efmer** [comment]
If the Project url is different from the dropdown Project url, the user defined changed url is used.
Temp project name:  Project defined by changed url

Added V 1.24
